language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t dgesteves/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dgesteves/docker-react npm run test